import { Router } from "express";
import * as controller from "../controllers/adminController.js";
import * as leadController from "../controllers/leadController.js";
import { adminOnly, authMiddleware } from "../middleware/authMiddleware.js";

export const adminRoutes = Router();
adminRoutes.use(authMiddleware, adminOnly);
adminRoutes.get("/overview", controller.overview);
adminRoutes.get("/slug", controller.checkSlug);
adminRoutes.post("/connect", controller.connectStore);
adminRoutes.get("/payments", controller.listPayments);
adminRoutes.delete("/payments/:id", controller.cancelPayment);
adminRoutes.get("/reports", controller.listReports);
adminRoutes.get("/journal", controller.listJournal);
adminRoutes.get("/backups", controller.listBackups);
adminRoutes.post("/backups", controller.startBackup);
adminRoutes.get("/owners", controller.listOwners);
adminRoutes.post("/owners", controller.createOwner);
adminRoutes.get("/owners/:id", controller.getOwner);
adminRoutes.patch("/owners/:id", controller.updateOwner);
adminRoutes.post("/owners/:id/change-password", controller.changeOwnerPassword);
adminRoutes.delete("/owners/:id", controller.deleteOwner);
adminRoutes.post("/owners/:id/impersonate", controller.impersonateOwner);
adminRoutes.get("/stores", controller.listStores);
adminRoutes.post("/stores", controller.createStore);
adminRoutes.get("/stores/:id", controller.getStore);
adminRoutes.patch("/stores/:id", controller.updateStore);
adminRoutes.delete("/stores/:id", controller.deleteStore);
adminRoutes.post("/stores/:id/extend-subscription", controller.extendSubscription);
adminRoutes.post("/stores/:id/payments", controller.acceptPayment);
adminRoutes.post("/stores/:id/disable", controller.disableStore);
adminRoutes.post("/stores/:id/enable", controller.enableStore);
adminRoutes.post("/stores/:id/archive", controller.archiveStore);
adminRoutes.post("/stores/:id/restore", controller.restoreStore);
adminRoutes.post("/stores/:id/enable-ai-form", controller.enableAiForm);
adminRoutes.post("/stores/:id/disable-ai-form", controller.disableAiForm);
adminRoutes.get("/leads", leadController.listLeads);
adminRoutes.patch("/leads/:id", leadController.updateLead);
