import { Router } from "express";
import * as controller from "../controllers/ownerController.js";
import { authMiddleware, logActionsAsOwner, ownerOnly } from "../middleware/authMiddleware.js";
import { aiDraftUpload, bulkAiDraftUpload, upload } from "../middleware/upload.js";

export const ownerRoutes = Router();
ownerRoutes.use(authMiddleware, ownerOnly, logActionsAsOwner);
ownerRoutes.get("/support", controller.getSupport);
ownerRoutes.get("/stores", controller.listStores);
ownerRoutes.get("/stores/:storeId", controller.getStore);
ownerRoutes.patch("/stores/:storeId", controller.updateStore);
ownerRoutes.post("/stores/:storeId/logo", upload.single("logo"), controller.updateStoreLogo);
ownerRoutes.get("/stores/:storeId/analytics", controller.getAnalytics);
ownerRoutes.get("/stores/:storeId/subscription", controller.getSubscription);
ownerRoutes.get("/stores/:storeId/products", controller.listProducts);
ownerRoutes.post("/stores/:storeId/products/ai-draft", aiDraftUpload.fields([{ name: "voice", maxCount: 1 }, { name: "images", maxCount: 8 }]), controller.createProductDraft);
ownerRoutes.post("/stores/:storeId/products/bulk-ai-draft", bulkAiDraftUpload.fields([{ name: "voice", maxCount: 1 }, { name: "images", maxCount: 40 }]), controller.createBulkProductDraft);
ownerRoutes.post("/stores/:storeId/products", controller.createProduct);
ownerRoutes.get("/stores/:storeId/products/:id", controller.getProduct);
ownerRoutes.patch("/stores/:storeId/products/:id", controller.updateProduct);
ownerRoutes.delete("/stores/:storeId/products/:id", controller.deleteProduct);
ownerRoutes.post("/stores/:storeId/products/:id/images", upload.single("image"), controller.addImage);
ownerRoutes.patch("/stores/:storeId/products/:id/images/order", controller.reorderImages);
ownerRoutes.delete("/stores/:storeId/products/:id/images/:imageId", controller.deleteImage);
